BaseURL: "https://words.yudocaa.in/"
languageCode: "en-us"
title: "Intellectual Web"
pygmentsstyle: 'monokai'

# Theme settings
theme: slim
paginate: 1000
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
params:
  Subtitle: ""
  mainSections: ["blog"]
  GithubID: "sayanchowdhury"
  TwitterID: "yudocaa"
  FacebookID: "yudocaa"
