BaseURL: "https://words.yudocaa.in/"
languageCode: "en-us"
title: "Intellectual Web"
pygmentsstyle: 'monokai'
disableKinds: ["section"]

# Theme settings
theme: slim
paginate: 1000
params:
  Subtitle: ""
  mainSections: ["blog"]
  GithubID: "sayanchowdhury"
  TwitterID: "yudocaa"
  FacebookID: "yudocaa"
