#BaseURL: "https://words.yudocaa.in/"
#languageCode: "en-us"
#title: "Intellectual Web"
#pygmentsstyle: 'monokai'
## disableKinds: ["section"]

## Theme settings
#theme: kiss-em
#paginate: 1000
#params:
  #Subtitle: ""
  ## mainSections: ["blog"]
  #GithubID: "sayanchowdhury"
  #TwitterID: "yudocaa"
  #FacebookID: "yudocaa"

baseurl = "https://stg.words.yudocaa.in"
languageCode = "en"
theme = "kiss-em"
Paginate = 5 # Number of posts per page
enableRobotsTXT = true
defaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "Intellectual Web"
    weight = 1

[params.microblog]
number = 2

[params.rss]
enable = true
includeContent = true
authorName = "Sayan Chowdhury "
authorEmail = "namoskar@yudocaa.in"

[params.info]
poweredby = true
related = true
copyright = "© <a href=\"https://github.com/sayanchowdhury\">Sayan Chowdhury</a> 2021"

[params.social]
about = "about"
twitter = "@yudocaa"
github = "sayanchowdhury"
email = "namoskar@yudocaa.in"
rss = "index.xml"

# Define the order of the icons:
[params.social.config]
platforms = ["about", "email", "github", "twitter", "xing", "rss"]

[taxonomies]
tag ="tags"


