baseURL: "https://words.yudocaa.in"
languageCode: "en-us"
title: "Intellectual Web"
pygmentsstyle: 'monokai'

# Theme settings
theme: slim
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
